"""initial schema

Revision ID: 1bc760c13d7b
Revises: 
Create Date: 2026-03-23 12:04:25.611991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc760c13d7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('focus_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('technique', sa.Enum('pomodoro', 'flowtime', 'bolsa', name='technique'), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('task_tags', sa.JSON(), nullable=True),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_work_seconds', sa.Integer(), nullable=False),
    sa.Column('total_break_seconds', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('interruptions', sa.JSON(), nullable=True),
    sa.Column('technique_config', sa.JSON(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('mood_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focus_sessions_id'), 'focus_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_focus_sessions_user_id'), 'focus_sessions', ['user_id'], unique=False)
    op.create_table('pomodoro_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('focus_interval_sec', sa.Integer(), nullable=False),
    sa.Column('short_break_sec', sa.Integer(), nullable=False),
    sa.Column('long_break_sec', sa.Integer(), nullable=False),
    sa.Column('pomodoros_target', sa.Integer(), nullable=False),
    sa.Column('pomodoros_completed', sa.Integer(), nullable=False),
    sa.Column('pomodoro_number', sa.Integer(), nullable=False),
    sa.Column('was_voided', sa.Boolean(), nullable=False),
    sa.Column('strict_mode', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['focus_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pomodoro_details_id'), 'pomodoro_details', ['id'], unique=False)
    op.create_index(op.f('ix_pomodoro_details_session_id'), 'pomodoro_details', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pomodoro_details_session_id'), table_name='pomodoro_details')
    op.drop_index(op.f('ix_pomodoro_details_id'), table_name='pomodoro_details')
    op.drop_table('pomodoro_details')
    op.drop_index(op.f('ix_focus_sessions_user_id'), table_name='focus_sessions')
    op.drop_index(op.f('ix_focus_sessions_id'), table_name='focus_sessions')
    op.drop_table('focus_sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###